databases:
  - name: taskmanager-db
    databaseName: taskmanager
    user: taskmanager

services:
  - type: web
    name: task-manager-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.16
    autoDeploy: false